### ISSUE TITLE
monitoring multiple interfaces?

### ISSUE THREAD

**Issue by schwo** [google/stenographer#102]
What is the recommended configuration for monitoring multiple interfaces with stenographer?

**Comment by gconnell** [comment]
Hey, great question!

There's two ways I can think of initially.

The first, and simplest, is to run two stenographer processes.  To do this,
just create a second config file and use stenographer's --config flag to
point at it.  You'll probably want to copy /etc/init/stenographer as well,
so upstart can handle the second process.

The second method you could use is a bond[1] interface.  This has some
limitations, in particular you can't distinguish between packets coming
from each interface.  But that could be a good thing, since it means that
you only have to query steno once.  So this is probably a better approach
if the traffic across both interfaces is distinct (like, no conflicting
rfc1918 addresses.

We could modify stenographer tp start up multiple stenotypes for different
interfaces.  That would require a good bit of work though, in particular
backwards incompatible changes to the configuration.  Might be a good
long-term goal, though!

  --Graeme

[1]
http://www.cyberciti.biz/howto/question/static/linux-ethernet-bonding-driver-howto.php

**Comment by gconnell** [comment]
BTW, http://linux-ip.net/html/ether-bonding.html is a much simpler
description of bond interfaces.

**Comment by schwo** [comment]
thanks!
